// Smoke test: ensure schema + modules load + views render.
require('dotenv').config();
const { ensureSchema } = require('../src/db');
ensureSchema();
console.log('schema OK');
require('../src/streamManager');
require('../src/transcoder');
require('../src/downloader');
require('../src/scheduler');
require('../src/looper');
require('../src/audioManager');
require('../src/youtubeManager');
require('../src/youtubeUploader');
require('../src/auth');
require('../src/routes/auth');
require('../src/routes/videos');
require('../src/routes/streams');
require('../src/routes/schedules');
require('../src/routes/looper');
require('../src/routes/audio');
require('../src/routes/youtube');
console.log('modules OK');
require('./render-check');
